name: Deploy
on:
  workflow_dispatch:
    inputs:
      region:
        description: "Enter the AWS region (e.g., us-east-2)"
        required: true

env:
  AWS_REGION: ${{ github.event.inputs.region }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}
      - name: chmod
        run: chmod -R +x ./.github *.sh
      - run: |
          ./deploy.sh